apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config-one
  namespace: default
data:
  special.how: very
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config-two
  namespace: default
data:
  log_level: INFO
