apiVersion: v1
kind: Pod
metadata:
  name: consume-via-vol
spec:
  containers:
    - name: consuming-container
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh","-c","ls /etc/config/" ]
      volumeMounts:
      - name: config-volume
        mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        name: myconfigmap
        items:
        - key: name
          path: name
        - key: city
          path: city
  restartPolicy: Never
